[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
reveal = "9Szz8bFZzV4CSv6WdhFFSLusYLQpTvzXCvtTZ78c19Dd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/mikemaccana/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
