[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
escrow_new = "8atVt41JaLmrLmCUgP8N9jEkc3KHwk5EV4AUYRxnqcix"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/mikemaccana/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
